version: pre-0.0.1#{build}
image: Visual Studio 2017
configuration: Release
build:
  project: OpenMC2.sln
  verbosity: minimal
after_build:
- cmd: 7z a OpenMC2.zip .\Release\OpenMC2.exe .\mc2.dll
artifacts:
- path: OpenMC2.zip
  name: zip-archive
deploy:
- provider: GitHub
  auth_token:
    secure: US2B1AJBegrxUhjKUfbocWUqavl636DxnaUnl8a7/waGexpd5Dp/mN6JBZIS+6Ee
  artifact: zip-archive
  on:
    appveyor_repo_tag: true